# TP2: Pivot de Gauss

Le thème de ce TP est la résolution de systèmes d'équations linéaires de la forme
\begin{equation*}
Ax = b,
\end{equation*}
pour une matrice $A\in M_n(\mathbb R)$ et un vecteur $b\in M_{n,1}(\mathbb R)$, par la méthode du pivot de Gauss.

Nous utiliserons les librairies numpy et numpy.linalg.

In [1]:
from numpy import *;
from numpy.linalg import *;

La librairie *numpy* introduit le type *ndarray* qui permet de faire du calcul matriciel. La commande *array* transforme une liste de listes en une matrice : pour définir la matrice $A$ on entre 
\begin{equation*}
A=\text{array}([[a_{11},\ldots,a_{1m}],\ldots,[a_{n1},\ldots,a_{nm}]]).
\end{equation*}
Pour multiplier deux matrices de tailles adaptées on utilise la commande *dot*. Pour concaténer des matrices la commande *concatenate*.

Définir les matrices
\begin{equation*}
A=\left(
\begin{array}{cccc}
1 & 2 & 3 & 4 \\
4 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{array}
\right)
\quad\text{et}\quad 
B=\left(
\begin{array}{cc}
1&2\\
3&4\\
5&6\\
7&8
\end{array}
\right),
\end{equation*}
calculer le produit $AB$, et tester les commandes A[0,2], A[0,:], A[[0,2],:], B[:,1], A[2,1:], A[[0,2],:3], A[0:2,1:3], concatenate ((A,B[:3,:]),axis=1).

Attention, quand on affecte une sous-matrice à une nouvelle matrice, l'espace mémoire n'est pas dupliqué. Pour dupliquer l'expace mémoire il faut créer une nouvelle matrice avec *array*. Tester la suite de commandes C=A[1,:]; C[1]=0; print A; print C, et comparer avec C=array(A[1,:]); C[1]=-1; print A; print C.

## Un exemple

* Définir la matrice $A$ et le vecteur $b$ correspondant au système linéaire suivant :
\begin{equation*}
\left\lbrace
\begin{array}{rcrcrl}
2x_1&+&4x_2&-&x_3&= 1\\
4x_1&&&-&2x_3&=0\\
x_1&+&2x_2&+&x_3&=2
\end{array}
\right.
\end{equation*}


Attention: Utiliser des nombres au format *float*. 

Résoudre le système en utilisant la méthode du pivot de Gauss: les seules opérations élémentaires autorisées sont les permutations de lignes
\begin{equation*}
L_i \leftrightarrow L_j,
\end{equation*}
les dilatations de lignes
\begin{equation*}
L_i \leftarrow \alpha L_i,\quad \alpha\neq 0,
\end{equation*}
et les transvections
\begin{equation*}
L_i \leftarrow L_i + \lambda L_j,\quad j\neq i.
\end{equation*}

* On définira, à l'aide de la commande concatenate, la matrice $C\in M_{3,4}(\mathbb R)$ dont les 3 premières colonnes correspondent à la matrice $A$, et la dernière colonne au vecteur $b$. Cette matrice $C$ représente complètement notre système linéaire.

* On effectuera sur la matrice $C$ les opérations élémentaires correspondant à chaque étape : à la dernière étape, on doit arriver à une matrice de la forme
\begin{equation*}
C_{sol}=
\left(
\begin{array}{cccc}
1&0&0&\hat b_1\\
0&1&0&\hat b_2\\
0&0&1&\hat b_3
\end{array}
\right),
\end{equation*}
qui correspond au système
\begin{equation*}
\left\lbrace
\begin{array}{rcrcrl}
x_1&&&&&=\hat b_1\\
&&x_2&&&=\hat b_2\\
&&&&x_3&=\hat b_3.
\end{array}
\right.
\end{equation*}

* Attention: Python numérote à partir de 0.

## Opérations élémentaires

* Créer des fonctions Perm, Dil, Trans qui prennent en argument une matrice et les paramètres d'une opération élémentaire sur les lignes, et renvoient la matrice modifiée en conséquence. Les tester sur la matrice
\begin{equation*}
M=\left(
\begin{array}{ccc}
1&1&-1\\
1&0&0\\
2&0& 1\\
3&-2&0
\end{array}
\right).
\end{equation*}


## Résoudre un système triangulaire inversible

L'algorithme du pivot de Gauss permet, en utilisant uniquement des opérations élémentaires sur les lignes, de transformer un système linéaire quelconque en un système **échelonné**. C'est-à-dire un système qui s'écrit sous la forme
$$Ex=b,$$
où la matrice $E$ est telle que : quand on passe d'une ligne à la suivante, le nombre de zéros en début de ligne augmente strictement. Une fois le système mis sous cette forme, il devient relativement facile à résoudre, en utilisant seulement des transvections sur les lignes.

Dans le cas d'une matrice carrée inversible, un système échelonné correspond à une matrice triangulaire supérieure dont tous les éléments diagonaux sont non nuls -- par exemple égaux à 1, quitte à dilater les lignes :
\begin{equation*}
E=\left(
\begin{array}{ccc}
1&&(e_{ij})\\
&\ddots & \\
(0)&& 1
\end{array}
\right)
\end{equation*}


* Ecrire une fonction SolTriang qui prend en argument une matrice dont les $n$ premières colonnes (où $n$ est le nombre de lignes) forment une matrice $E$ triangulaire supérieure avec des 1 sur sa diagonale, et qui renvoie la matrice modifiée par la suite de transvections permettant de transformer $E$ en la matrice identité. La tester en résolvant les systèmes
\begin{align*}
&\left\lbrace
\begin{array}{rcrcrl}
x_1 & + & x_2 &- &2 x_3 & =0\\
&&x_2 &+&3x_3&=-1\\
&&&&x_3&=1
\end{array}
\right.\\
&\left\lbrace
\begin{array}{rcrcrcrl}
x_1&-&2x_2&+&x_3&+&5x_4&=2\\
&&x_2&+&3x_3&-&x_4&=0\\
&&&&x_3&+&4x_4&=1\\
&&&&&&x_4&=-1
\end{array}
\right.
\end{align*}

[[ 1  1 -2  0]
 [ 0  1  3 -1]
 [ 0  0  1  1]]
[[ 1.  0.  0.  6.]
 [ 0.  1.  0. -4.]
 [ 0.  0.  1.  1.]]


[[ 1. -2.  1.  5.  2.]
 [ 0.  1.  3. -1.  0.]
 [ 0.  0.  1.  4.  1.]
 [ 0.  0.  0.  1. -1.]]
[[  1.   0.   0.   0. -30.]
 [  0.   1.   0.   0. -16.]
 [  0.   0.   1.   0.   5.]
 [  0.   0.   0.   1.  -1.]]


## Choix d'un pivot

On définit une fonction ChoixPivot qui prend en argument une matrice, trouve dans sa première colonne un élément non nul, puis permute et dilate des lignes pour renvoyer une matrice modifiée dans laquelle le pivot est en première ligne et égal à 1. Si ce n'est pas possible, la fonction affiche un message d'erreur et renvoie None. 

La tester sur la matrice $A$ du début de l'énoncé, et sur les matrices 
\begin{equation*}
\left(\begin{array}{cccc}
0&0&1&0\\
1&0&0&1\\
2&1&3&0
\end{array}
\right),
\qquad
\left(\begin{array}{ccc}
0&1&0\\
0&0&2
\end{array}
\right).
\end{equation*}

## Etape de pivot

Définir une fonction EtapePivot qui prend en argument une matrice dont le premier coefficient de la première colonne est égal à 1 (car on lui aura préalablement appliqué la fonction ChoixPivot), qui effectue les transvections nécessaires pour annuler tous les autres coefficients de la première colonne, et qui renvoie la matrice ainsi obtenue.

La tester sur la matrice $A$ du début de l'énoncé (après application de ChoixPivot).


## Transformation en un système triangulaire inversible

Définir de manière récursive une fonction TriangPivot qui prend en argument une matrice correspondant à un système inversible (i.e. les $n$ premières colonnes, où $n$ est le nombre de lignes, forment une matrice carrée inversible) et renvoie une matrice correspondant à un système triangulaire supérieur avec des 1 sur la diagonale, obtenue par une suite d'opérations élémentaires. Si le système n'est pas inversible, la fonction renvoie un message d'erreur.

## Résolution d'un système inversible et calcul d'inverse

* Ecrire, en utilisant les fonctions TriangPivot et SolTriang, une fonction Sol qui prend en argument une matrice correspondant à un système inversible, et qui renvoie la matrice correspondant à la dernière étape du pivot de Gauss, dans laquelle la solution se lit sur la dernière colonne. La tester sur l'exemple du début.

* Comment utiliser cette fonction pour calculer l'inverse d'une matrice inversible?

* On pourra comparer les résultats avec les fonctions solve et inv de numpy.linalg.

## Retour sur le choix du pivot

Ecrire une fonction ChoixPivotMax qui fait la même chose que la fonction ChoixPivot, mais en choisissant comme pivot l'élément de valeur absolue maximale.
On pourra utiliser les fonctions *abs* et *max*. Il pourra être utile de transformer la première colonne en liste (list) pour pouvoir utiliser l'attribut list.index.

Ecrire les fonctions TriangPivotMax et SolMax correspondantes, et les tester sur le système
\begin{equation*}
\left\lbrace
\begin{array}{rcrcrcrl}
x & + & 2y & + & 5z &+& 4t& =1\\
6x & +& 8y&-&5z&+&6t&=2\\
-5x&+&7y&+&z&+&6t&=3\\
3x&+&4y&+&7z&+&8t&=4.
\end{array}
\right.
\end{equation*}
Comparer avec TriangPivot et Sol.

## Le pivot de Gauss dans le cas général

*Cette question est difficile et facultative*

Ecrire une fonction  qui applique l'algorithme du pivot de Gauss pour donner toutes les solutions d'un système d'équations linéaires quelconque (pas nécessairement carré, ni inversible).